CREATE TABLE recipro_fridge_items (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    modified TIMESTAMP DEFAULT now() NOT NULL,
    expiration TEXT NOT NULL,
    note TEXT,
    categoryid INTEGER REFERENCES recipro_fridge_categories(id) ON DELETE CASCADE NOT NULL,
    userid INTEGER REFERENCES recipro_users(id) ON DELETE CASCADE NOT NULL
);